workflows:
  release-testflight:
    environment:
      node: 14.19.0
      npm: latest
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Install cordova deps
        working_directory: ./cordova
        script: npm install

      - name: Build web contents
        script: npm run build-prod

      - name: Build cordova distribution
        script: npm run cordova-dist

      - name: Add ios to cordova build
        working_directory: ./cordova
        run: npm run add-ios

      - name: Build ios
        working_directory: ./cordova
        run: npm run cordova-build
