

default_platform(:ios)


platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(
      type: 'appstore',
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"])
    )
    increment_build_number(xcodeproj: "pasco.xcodeproj", build_number: ENV["BUILD_NO"])
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: false)
  end
end
