# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore', git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]))
    increment_build_number(xcodeproj: "pasco.xcodeproj")
    build_app(workspace: "pasco.xcworkspace", scheme: "pasco")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
