#!/bin/sh
DIR=$(dirname $(dirname $0))
DIST=$1

cp -r $DIR/html/* $DIST && sed -i "" -e "s%<!-- INJECT SCRIPTS -->%<script src=\"cordova.js\"></script>%" $DIST/index.html && sed -i "" -e "s%ws://localhost:3000%data: gap: https://ssl.gstatic.com%" $DIST/index.html
