#!/bin/sh
DIR=$(dirname $(dirname $0))
DIST=$1

HTML_FILES="$DIST/index.html $DIST/edit-config.html $DIST/quick-setup.html $DIST/help.html"

cp -r $DIR/html/* $DIST && rm $DIST/css/.gitignore && sed -i "" -e "s%<!-- INJECT SCRIPTS -->%<script src=\"cordova.js\"></script>%" $HTML_FILES && sed -i "" -e "s%<!-- INJECT HEAD -->%%" $HTML_FILES  && sed -i "" -e "s%ws://localhost:3000%data: gap: https://ssl.gstatic.com%" $HTML_FILES
