name: Run Cypress 
on: [pull_request]
jobs:
  RunCypress:
    runs-on: windows-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npm install

      - uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}

