name: Run Cypress 
on: [pull_request]
jobs:
  RunCypress:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npm install

      - uses: cypress-io/github-action@v2
        with:
          install: false
