name: Release Beta
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
concurrency:
  group: deploy-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install root dependencies
        run: npm install

      - name: Install cordova dependencies
        working-directory: ./cordova
        run: npm install

      - name: Build web contents
        run: npm run build-prod

      - name: Create cordova distribution
        run: npm run cordova-dist

      - name: Run cordova build
        working-directory: ./cordova
        run: npm run cordova-build
